#!/usr/bin/env bash
# Concatenates the database setup into two paste-ready files:
#   supabase/deploy/full_install.sql — new project: schema + seed + every migration
#   supabase/deploy/upgrade_v2.28_to_latest.sql — existing install already at v2.27
# Run after adding a migration; CI fails if the committed bundles are stale.
set -euo pipefail
cd "$(dirname "$0")/.."
out=supabase/deploy
mkdir -p "$out"
header() {
  echo "-- ============================================================================"
  echo "-- GENERATED by scripts/build-sql-bundles.sh — do not edit by hand."
  echo "-- $1"
  echo "-- ============================================================================"
}
{
  header "Fresh install: schema.sql + seed.sql + supabase/migrations/v2.* in order."
  for f in supabase/schema.sql supabase/seed.sql $(ls supabase/migrations/v2.*.sql | sort -V); do
    printf '\n-- >>>>>>>>>> %s\n' "$f"; cat "$f"; printf '\n'
  done
} > "$out/full_install.sql"
{
  header "Upgrade an install that already ran v2.27 (and earlier) to the latest version."
  for f in $(ls supabase/migrations/v2.*.sql | sort -V | awk -F'v2.' '{split($2,a,"_"); if (a[1]+0 >= 28) print}'); do
    printf '\n-- >>>>>>>>>> %s\n' "$f"; cat "$f"; printf '\n'
  done
} > "$out/upgrade_v2.28_to_latest.sql"
echo "wrote $out/full_install.sql and $out/upgrade_v2.28_to_latest.sql"
